name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build WebApp Docker image
      run: docker build ./ChristianBookClub.Web/Dockerfile --file Dockerfile --tag christian_book_club_webapp:$(date +%s)
